### ISSUE TITLE
Provide Country Name vs. Country Code

### ISSUE THREAD

**Issue by boldtrn** [gisgraphy/gisgraphy#20]
I have seen that gisgraphy returns only the country code, but not the country name. Why is there no country? Gisgraphy provides admin levels as full text, but not the country. I would have expected the result to contain the country name as well.

**Comment by gisgraphy** [comment]
The country code is used to filtered results. The country has never been asked or added by anyone but can be easilly added to the feed by a little peace of codeDavid Masclet-------- Message original --------Objet : [gisgraphy/gisgraphy] Provide Country Name vs. Country Code (#20)De : Robin À : gisgraphy/gisgraphy Cc : Subscribed I have seen that gisgraphy returns only the country code, but not the country name. Why is there no country? Gisgraphy provides admin levels as full text, but not the country. I would have expected the result to contain the country name as well.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gisgraphy/gisgraphy","title":"gisgraphy/gisgraphy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gisgraphy/gisgraphy"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Provide Country Name vs. Country Code (#20)"}],"action":{"name":"View Issue","url":"https://github.com/gisgraphy/gisgraphy/issues/20"}}}

**Comment by boldtrn** [comment]
> The country has never been asked or added by anyone but can be easilly added to the feed by a little peace of code

I'd say let's do it then :). If it is not negatively impacting performance or a big development overhead, it can't hurt. 

My reason was that in this [PR](https://github.com/graphhopper/geocoder-converter/pull/34) we are doing the conversion from country code to country name. I think there might be other clients/users that would prefer to use the country name. I always prefer to have "stupid clients" and servers providing all the required information, without too much conversion.

**Comment by gisgraphy** [comment]
done ! 317d16664ca3edb50d1a5553f321d42616f62f46

**Comment by gisgraphy** [comment]
in geocoding service too f0af8555a26a971834947ffcbe4f02c1dcf462e1
