### ISSUE TITLE
Cannot find OSM Node Name

### ISSUE THREAD

**Issue by boldtrn** [gisgraphy/gisgraphy#21]
I was playing around with gisgraphy a bit and saw that I could not find nodes, that I knew are in OSM.

For example "Bistro City", which is in OSM and found by Nominatm, but not by Geonames, see [here](http://www.openstreetmap.org/search?query=bistro%20city#map=19/48.68917/9.42206&layers=D). I tried many other OSM nodes.

Is this a known limitation?

Mabe related to #18? But #18 is about results being in Geonames that are missing.

**Comment by gisgraphy** [comment]
https://services.gisgraphy.com/fulltext/?q=bistro%20city&style=fullYou probably have usef the geocoder? It only find addresses. The fulltext engine find place /poiIt is a separate process. Note that suggest find place and addresses. -------- Message original --------Objet : [gisgraphy/gisgraphy] Cannot find OSM Node Name (#21)De : Robin À : gisgraphy/gisgraphy Cc : Subscribed I was playing around with gisgraphy a bit and saw that I could not find nodes, that I knew are in OSM.
For example "Bistro City", which is in OSM and found by Nominatm, but not by Geonames, see here. I tried many other OSM nodes.
Is this a known limitation?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gisgraphy/gisgraphy","title":"gisgraphy/gisgraphy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gisgraphy/gisgraphy"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Cannot find OSM Node Name (#21)"}],"action":{"name":"View Issue","url":"https://github.com/gisgraphy/gisgraphy/issues/21"}}}

**Comment by boldtrn** [comment]
Yes you are right, it works with fulltext but not with geocoding
